// <auto-generated />
namespace MVC5_full_version.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class stru2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stru2));
        
        string IMigrationMetadata.Id
        {
            get { return "201712300131073_stru2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
