// <auto-generated />
namespace MVC5_full_version.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class first1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first1));
        
        string IMigrationMetadata.Id
        {
            get { return "201801182023379_first1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
