//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CottonCandy.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterViewModel
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string ReferalCode { get; set; }
        public System.DateTime UserCreatedDate { get; set; }
        public string IPAddress { get; set; }
        public string ImagePath { get; set; }
    }
}
